name: MedFleet
options:
  bundleIdPrefix: net.medfleet
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true

settings:
  ENABLE_PREVIEWS: NO
  ENABLE_DEBUG_DYLIB: NO

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 11.6.0

targets:
  MedFleet:
    type: application
    platform: iOS
    sources:
      - path: MedFleet
        excludes:
          - Info.plist
        includes:
          - "**/*.swift"
          - "**/*.xcassets"
          - GoogleService-Info.plist
          - MedFleet.entitlements
    configFiles:
      Debug: configs/signing.xcconfig
      Release: configs/signing.xcconfig
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: net.medfleet.rep
      MARKETING_VERSION: "1.1.6"
      CURRENT_PROJECT_VERSION: 8
      INFOPLIST_FILE: MedFleet/Info.plist
      CODE_SIGN_ENTITLEMENTS: MedFleet/MedFleet.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_TEAM: DZW782KNRM
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: Apple Distribution
      SWIFT_VERSION: "5.0"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      TARGETED_DEVICE_FAMILY: "1"
      SWIFT_EMIT_LOC_STRINGS: YES
      ENABLE_PREVIEWS: NO
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseCore
      - package: firebase-ios-sdk
        product: FirebaseMessaging

